### ISSUE TITLE
Provide mutation query

### ISSUE THREAD

**Issue by andreasblueher** [oktadev/okta-express-graphql-example#1]
Hey Braden,

thank you very much for this example. It really helped me to glue together different peaces I hadn't been able to use together. However, since typing the whole mutation query for the GraphQL playground I was wondering if you could add it to the readme or your blog. Thanks!

**Comment by redbmk** [comment]
Hi @andreasblueher , thanks for the suggestion! I hadn't thought to include a copyable version of the text. I've added the examples to the README and sent a fix to the blog post too.
