### ISSUE TITLE
Blog typo

### ISSUE THREAD

**Issue by andreasblueher** [oktadev/okta-express-graphql-example#2]
Hey Braden, 

there seems to be a typo in the npm i command where you install @okta/oidc-middleware and so forth where you put in

> @okta/oidc-sdk-nodejs

where from you package.json you meant to use 

> @okta/okta-sdk-nodejs

there. Hope it helps

**Comment by johnbcable** [comment]
> Hey Braden,
> 
> there seems to be a typo in the npm i command where you install @okta/oidc-middleware and so forth where you put in
> 
> > @okta/oidc-sdk-nodejs
> 
> where from you package.json you meant to use
> 
> > @okta/okta-sdk-nodejs
> 
> there. Hope it helps

This does not, I'm afraid. I still get the same in-browser error screen when visiting http://localhost:4000/access-token as I sent through before. My modified package.json (from the GitHub example set) is included below - does this still need the @okta/oidc-middleware (as the browser error message still references an oidc error (as before))?

package.json
=======================================
{
  "name": "graphql-express",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "standard",
    "start": "nodemon ."
  },
  "keywords": [],
  "author": "",
  "license": "Apache 2.0",
  "dependencies": {
    "@okta/jwt-verifier": "0.0.12",
    "@okta/oidc-middleware": "^1.0.0",
    "@okta/okta-sdk-nodejs": "^1.2.0",
    "cors": "^2.8.4",
    "dotenv": "^6.0.0",
    "express": "^4.16.3",
    "express-graphql": "^0.6.12",
    "express-session": "^1.15.6",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.9.2",
    "standard": "^12.0.1",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "nodemon": "^1.18.4"
  }
}

**Comment by redbmk** [comment]
Hi @andreasblueher, thanks for catching that! I just submitted a PR to fix the post.

**Comment by andreasblueher** [comment]
Hey @redbmk looking again at the blog post I cannot see this being fixed.

On another note 

> echo "APP_SECRET=`openssl rand -base64 32`" >> .env

This only works on linux/mac and does not work for windows. I found a website which created a base64 string for me to work around this.

**Comment by andreasblueher** [comment]
Also what do you think about referencing the github repo earlier, so people might jump there before the end of the blogpost.

**Comment by redbmk** [comment]
> Hey @redbmk looking again at the blog post I cannot see this being fixed.

I submitted a PR: https://github.com/okta/okta.github.io/pull/2404. Once that gets merged, the blog post should update. I'm waiting to close this issue until that happens.

> 
> On another note
> 
> > echo "APP_SECRET=`openssl rand -base64 32`" >> .env
> 
> This only works on linux/mac and does not work for windows. I found a website which created a base64 string for me to work around this.

That's a good point - I hadn't tried that on windows.

I think a more universal solution would be:

```
npm install -g uuid-cli
echo "APP_SECRET=`uuid`" >> .env
```

I just updated the README and submitted a PR to the blog: https://github.com/okta/okta.github.io/pull/2406

> Also what do you think about referencing the github repo earlier, so people might jump there before the end of the blogpost.

Yeah I can do that. Here's another PR where I added a little blurb earlier on: https://github.com/okta/okta.github.io/pull/2407

**Comment by redbmk** [comment]
Looks like those are all merged now!

**Comment by andreasblueher** [comment]
Thank you very much! Great work!
